Loading da página de login
wandersoncbjr/Proc.-Sel.-de-Dev-Instituto-Taqtile pull request #13
Opened 2023-04-01 02:58 UTC by wandersoncbjr

**Uma print do loading** 
![image](https://user-images.githubusercontent.com/101597114/229262453-930d0e94-68d4-4677-b416-80f0179d2ab3.png)

**Print da nova rota** 
![image](https://user-images.githubusercontent.com/101597114/229262503-1a91ab75-a9e4-4246-acc4-4181e8231434.png)

**Tentei deixar um pouco responsivo**

![image](https://user-images.githubusercontent.com/101597114/229262541-aa57e378-d87b-4202-9cca-640f7f5953ba.png)

2023-04-01 13:36 UTC, racsandoval commented on src/components/login/index.tsx
> +        <input type='submit' value='Acessar' className='btn-login' disabled={false} />
com o submit e o loading dessa forma, o usuário consegue dar submit mesmo com o loading ocorrendo
```
NOTE: while on load, the user should not be able to click on the button again.
This way we avoid performing the login request more times unecessarily.
```

2023-04-02 19:41 UTC, wandersoncbjr commented on src/components/login/index.tsx
> +        <input type='submit' value='Acessar' className='btn-login' disabled={false} />
>
Eu tinha alterado isso, acho que de alguam forma apaguei quando subi a alteração. perdão

2023-04-03 14:54 UTC, dan-ueno requested changes
um ponto é que a rota precisa validar se está de fato logado para conseguir entrar no /home

2023-04-03 15:03 UTC, dan-ueno approved these changes
se der, valida

2023-04-03 20:36 UTC, merged