Criação do Projeto
wandersoncbjr/Proc.-Sel.-de-Dev-Instituto-Taqtile pull request #5
Opened 2023-03-22 21:04 UTC by wandersoncbjr

configuração do prettier e eslint

2023-03-22 22:53 UTC, dan-ueno requested changes
já está bacana, só falta remover a pasta do vscode

2023-03-22 22:53 UTC, dan-ueno commented on .vscode/settings.json
> +{
vc pode deixar a pasta do vscode no git ignore.

2023-03-23 15:02 UTC, dan-ueno approved these changes

2023-03-23 15:42 UTC, racsandoval approved these changes

2023-03-23 15:42 UTC, racsandoval commented on src/App.test.tsx
> +test('renders learn react link', () => {
apenas um detalhe, mas como o arquivo `App.tsx` foi alterado, esse teste não funciona mais, poderia até deletar esse arquivo

2023-03-23 15:43 UTC, racsandoval commented on .eslintignore
> +.eslintrc.json
esse ícone vermelho aparece quando o arquivo não tem uma quebra de linha após o fim do conteúdo, pra fazer sumir basta adicionar uma quebra de linha no final

2023-03-23 17:12 UTC, merged