Implementando a validação do formulário de login.
wandersoncbjr/Proc.-Sel.-de-Dev-Instituto-Taqtile pull request #9
Opened 2023-03-25 01:35 UTC by wandersoncbjr

2023-03-25 01:38 UTC, wandersoncbjr commented
finish

2023-03-27 13:34 UTC, racsandoval commented
para facilitar o code review, poderia deixar o into como `screen/login` ao invés de `develop`. Dessa forma conseguimos ver apenas as diferenças entre essas duas branches, e não todas as alterações feitas nas duas branches criadas

2023-03-27 21:16 UTC, racsandoval commented on src/Login.tsx
> +      setMostraError(true);
um problema com essa lógica é que caso o usuário erre o formato de email e senha, primeiro receberia o erro do email, enviaria novamente o formulário, e só então receberia o erro da senha, que tal deixar a validação de cada campo independente e caso o usuário erre os dois, mostrar o erro nos dois campos?

2023-03-28 14:01 UTC, dan-ueno requested changes

2023-03-28 14:01 UTC, dan-ueno commented on src/Login.tsx
> +    function validacao(email: string, senha: string) {
a tag de input pode receber algumas props para realizar a validação, vale a pena pesquisar sobre quais as propriedades que ela pode receber ;)

2023-03-29 14:51 UTC, dan-ueno approved these changes

2023-03-29 17:15 UTC, racsandoval reviewed
não precisa realizar essa mudança, mas uma boa prática é que erros de input (como email no formado errado) pertençam ao input e não ao form todo, seria uma boa levantar essa discussão na daily, e quais as vantagens e o que muda fazendo dessa forma
<img width="391" alt="image" src="https://user-images.githubusercontent.com/46897228/228616777-e354917b-951d-4b6e-b9e4-3ebc8bdcd7e2.png">

2023-03-29 17:15 UTC, racsandoval commented on src/Login.tsx
> +    }
aqui não é necessário o `mostraErro`, apenas o estado de erro já seria suficiente e você consegue verifica no JSX se deve mostrar o erro pela quantidade de erros no estado
```suggestion
      setErros(erros);
```

2023-03-29 17:15 UTC, racsandoval commented on src/Login.tsx
> +  console.log(erros);
log

2023-03-29 17:15 UTC, racsandoval commented on src/Login.tsx
> +  }
aqui você poderia manter em duas funções `handleNameChange` e `handlePasswordChange`, me parece estranho usar a mesma função para os dois inputs

2023-03-29 17:15 UTC, racsandoval approved these changes

2023-03-29 17:39 UTC, merged